env:
  node: true
  mocha: true

extends:
  - airbnb-base

globals:
  artifacts: true
  web3: true
  contract: true
  assert: true

rules:
  comma-dangle:
    - error
    - arrays: always
      objects: always
      imports: never
      exports: never
      functions: ignore
